import 'dart:convert';
import 'dart:typed_data';

import 'package:fluxer_dart/fluxer_dart.dart';

/// `!upload [text]` — generates a small text file and sends it as an
/// attachment.
///
/// Sending a file is three steps, because the bytes never pass through
/// the API: plan the upload, `PUT` the bytes to the presigned storage URL
/// the plan returns, then claim the result on a message. Nothing is
/// visible until that third step, and each upload key can only be claimed
/// once.
Future<void> handleUpload(CommandContext context) async {
  final body = context.args.isEmpty
      ? 'Generated by the fluxer_dart example bot.'
      : context.args.join(' ');
  final bytes = Uint8List.fromList(utf8.encode(body));

  // Steps one and two: plan, then transfer.
  final attachment = await context.bot.attachments.uploadFile(
    context.message.channelId,
    filename: 'note.txt',
    bytes: bytes,
    contentType: 'text/plain',
    description: 'A note written by !upload',
  );

  // Step three: the file only exists once a message claims it.
  await context.reply(
    MessageBuilder(content: 'Here is that as a file:').attachment(attachment),
  );
}
